### ISSUE TITLE
Additional operation 2

### ISSUE THREAD

**Issue by Fwaith** [Fwaith/A-Text-Editor#12]

**Comment by BenIskauskas** [comment]
Potential operation:

"Search Line"

Where a specific phrase is searched for in a given file. If found, we return all the line numbers and contents on which the phrase was found.

"Join Files"

Where we take two file names as inputs and append the files together in the order they were inputted. Hence making a single new file.

"Split File"

Where we would take a file and a line number, then create a new file with all lines up to and including that line number, and another with the remaining lines. Basically splitting the files.
